analyzerIP: "10.100.3.111"  # "localhost"

# for sensor data streaming: 
# notice the header: [Mac] /Volumes/Data/  [Linux] /mnt/r/
sensor_folder_path: "/mnt/r/crd_optical_feedback_analyzer_rnd/SensorStream_logging"
save_interval: 60  # s, save a csv file every 1 min

# for save RDF file
optical_folder_path: "/mnt/r/crd_optical_feedback_analyzer_rnd/RDF_logging/20250203_6028_6228"
output_folder: "/mnt/r/crd_optical_feedback_analyzer_rnd/combined_data/20250203_6028_6228combo"



